### ISSUE TITLE
Will this work on the Jio Fi?

### ISSUE THREAD

**Issue by MysteriousLog6** [geekman/xqrepack#11]
Recently the Jio Fi 3 had received an unlocked firmware , the firmware seems to be an UBI file but I would like to see if I can use this script maybe? The firmware isn't rooted so I can show the names of the partitions.....

I was able to get this from a tweet of the person who made the firmware:
![image](https://user-images.githubusercontent.com/63236194/123435014-b921dd80-d5ea-11eb-8641-1f3fddf6b2a2.png)

**Comment by geekman** [comment]
This set of scripts has been made specifically for Xiaomi-based devices, so the short answer is **no**, it will not work on the Jio Fi.

However, most of these routers and access points run Linux, so it's possible to adapt the scripts to work on the Jio Fi (or any embedded device), but you need to understand how the Jio Fi system is structured and its internals in order to make it work. That is outside the scope of this project though.
