### ISSUE TITLE
Firmware Problems AX5 version 1.0.44

### ISSUE THREAD

**Issue by vapustovoyt** [geekman/xqrepack#17]
Hi. When repack firmware AX5 v 1.0.44, the router does not display the state of the WAN (Internet)port and does not connect to the Mi-Wi-fi application
p.s Sorry about other open and closed issue from other account :-)

**Comment by KaMyKaSii** [comment]
If you look at the commits you will see that this behavior is desired. The script remove all features that communicate with Chinese servers

**Comment by geekman** [comment]
Indeed. The WAN port check has been explicitly disabled because it pings China / Xiaomi's servers. As for the phone app I'm not too sure because I don't use it. It might not be working because there's many other services on the router which phones home to Xiaomi, so I have probably removed those as well.

In any case, these issues will not be fixed, because it was removed for user privacy.
