### ISSUE TITLE
Not working with newest CN Firmware miwifi_r3600_firmware_02d97_1.1.15.bin

### ISSUE THREAD

**Issue by FaserF** [geekman/xqrepack#5]
First, thank you very much for your work!
I have tried generating a new image with your script for the latest 1.1.15 version. 
It worked, I have flashed that, but afterwards my root access was lost.

It is working great for the version miwifi_r3600_all_f1e60_1.0.424.bin

P.S.: I managed to create a small homeassistant docker addon from your script (if someone is interested): https://github.com/FaserF/hassio-addons/tree/master/xqrepack

**Comment by FaserF** [comment]
I have just read #4 and it looks like my issue is similar to that one. Sorry for the "issue spam" then.

**Comment by geekman** [comment]
No worries.

I have released a new version, which should fix SSH access: https://github.com/geekman/xqrepack/releases/tag/v1.1

Please let me know if this works for you.

**Comment by FaserF** [comment]
Thank you! I have just updated my router to the latest 1.1.15 firmware (with xqflash).

the update worked but it looks like that again I lost SSH. I am now unable to sign in again via SSH.
(Permission denied, please try again)

**Comment by geekman** [comment]
> the update worked but it looks like that again I lost SSH. I am now unable to sign in again via SSH.
> (Permission denied, please try again)

This error indicates the SSH port is open, just that the password is wrong. 

The SSH password should be the same as what you used previously, before updating the firmware. If you factory reset the router, then the password should be reverted to `password`.

**Comment by FaserF** [comment]
Unfortunatly nothing does work:
password
my old SSH password
Router Web UI password


When I have time I will do a downgrade, enable SSH again and try a upgrade again with a new modded firmware by your script. But right now it seems the last try with your script and 1.1.15 doesnt work for me

**Comment by geekman** [comment]
One last possibility for the password might be one that is calculated from your router's serial number. You can compile and use  [mkxqimage_rev](https://github.com/NyaMisty/mkxqimage_rev) to generate a password from your serial number, or if you don't want the hassle to compile it yourself, you can use an online calculator created by someone else here: <https://www.oxygen7.cn/miwifi/>

This issue should have been fixed by 37ce46a878 already, which should then allow the router to retain the default password of `password` after a factory reset. I have just factory reset my router using the 1.1.15 firmware and it worked for me.

**Comment by FaserF** [comment]
Even with the generated password it doesnt work. 
I will give it a new try with a factory reset and upgrade the next days.
Thank you so much for your help.

**Comment by FaserF** [comment]
I still dont know why it didn't work, I have downgraded to the exploitable version, then installed a compiled version from your script again and now it is working great.
